### ISSUE TITLE
脚本不同子页面下，不能自动展开全文以及自动感谢

### ISSUE THREAD

**Issue by lyjhyjyes** [Eished/jkforum_helper#1]
脚本不同子页面下，不能自动展开全文以及自动感谢
https://www.jkforum.net/forum-525-1.html
https://www.jkforum.net/thread-13746617-1-1.html
https://www.jkforum.net/type-525-521.html
https://www.jkforum.net/forum.php?mod=viewthread&tid=13746617&extra=page%3D1%26filter%3Dtypeid%26typeid%3D521%26typeid%3D521
1是该版的全部，3是该版步兵分类，导致后缀不同。
2和4是同一个网页，4不会自动展开全文以及自动感谢，以及详细地址不同，导致4在返回1的情况下，标题没有识别历史记录、没有变成灰色。
可能涉及敏感链接，在greasyfork反馈需要人工审核，所以在GitHub上更加完善的反馈
感谢脚本

**Comment by lyjhyjyes** [comment]
> 脚本不同子页面下，不能自动展开全文以及自动感谢
> https://www.jkforum.net/forum-525-1.html
> https://www.jkforum.net/thread-13746617-1-1.html
> https://www.jkforum.net/type-525-521.html
> https://www.jkforum.net/forum.php?mod=viewthread&tid=13746617&extra=page%3D1%26filter%3Dtypeid%26typeid%3D521%26typeid%3D521
> 1是该版的全部，3是该版步兵分类，导致后缀不同。
> 2和4是同一个网页，4不会自动展开全文以及自动感谢，以及详细地址不同，导致4在返回1的情况下，标题没有识别历史记录、没有变成灰色。
> 可能涉及敏感链接，在greasyfork反馈需要人工审核，所以在GitHub上更加完善的反馈
> 感谢脚本

https://www.jkforum.net/forum-393-1.html
由于部分帖子使用了颜色标题，打开后标题不会变灰，无法标识已看。

**Comment by Eished** [comment]
> > 脚本不同子页面下，不能自动展开全文以及自动感谢
> > https://www.jkforum.net/forum-525-1.html
> > https://www.jkforum.net/thread-13746617-1-1.html
> > https://www.jkforum.net/type-525-521.html
> > https://www.jkforum.net/forum.php?mod=viewthread&tid=13746617&extra=page%3D1%26filter%3Dtypeid%26typeid%3D521%26typeid%3D521
> > 1是该版的全部，3是该版步兵分类，导致后缀不同。
> > 2和4是同一个网页，4不会自动展开全文以及自动感谢，以及详细地址不同，导致4在返回1的情况下，标题没有识别历史记录、没有变成灰色。
> > 可能涉及敏感链接，在greasyfork反馈需要人工审核，所以在GitHub上更加完善的反馈
> > 感谢脚本
> 
> https://www.jkforum.net/forum-393-1.html
> 由于部分帖子使用了颜色标题，打开后标题不会变灰，无法标识已看。

新版源码已去掉颜色标题
