### ISSUE TITLE
脚本0.8.8的一键回复失效

### ISSUE THREAD

**Issue by lyjhyjyes** [Eished/jkforum_helper#10]
win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。
下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。
之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。
是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢

**Comment by lyjhyjyes** [comment]
> win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。 下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。 之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。 是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢

原来“重置回帖数据”，部分板块需要手动输入回复，然后获取当前页码，不使用一键回复，刷新页面后，就能恢复正常。

**Comment by lyjhyjyes** [comment]
> win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。 下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。 之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。 是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢

新人报道专区，许多人的回复下自带超链接，比如“歡迎來到捷克論壇~~
請多多指教~也可以加我好友互相解任務喔~
另外~~~
小弟在申請好市民徽章，
請大大給予愛心並關注，
小弟也會盡力回送愛心~
請點下方的網址給予我愛心，
感謝您了~

https://www.jkforum.net/thread-17296783-1-1.html”
请问能否增加推广报道主页和个人空间主页的超链接功能，感谢。部分帖子需要100权限，努力刷到100

**Comment by Eished** [comment]
> > win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。 下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。 之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。 是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢
> 
> 新人报道专区，许多人的回复下自带超链接，比如“歡迎來到捷克論壇~~ 請多多指教~也可以加我好友互相解任務喔~ 另外~~~ 小弟在申請好市民徽章， 請大大給予愛心並關注， 小弟也會盡力回送愛心~ 請點下方的網址給予我愛心， 感謝您了~
> 
> [https://www.jkforum.net/thread-17296783-1-1.html”](https://www.jkforum.net/thread-17296783-1-1.html%E2%80%9D) 请问能否增加推广报道主页和个人空间主页的超链接功能，感谢。部分帖子需要100权限，努力刷到100

输入框一直是支持富文本的。在论坛编辑器的高级模式里编辑好，可以去复制别人的，点右上角纯文本，复制到回复里就可以回复富文本了。

**Comment by Eished** [comment]
> > win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。 下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。 之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。 是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢
> 
> 原来“重置回帖数据”，部分板块需要手动输入回复，然后获取当前页码，不使用一键回复，刷新页面后，就能恢复正常。

账号等级低，权限不够导致获取不到快速回复时只能手动输入回复，文档里有说。

**Comment by lyjhyjyes** [comment]
> > > win10下的chrome，早上随便打开一个板块，“获取当前页码”，然后“一键回复”，ok。 下午“重置回帖数据”，然后打开任何一个板块，告知“获取当前页码”没有权限，也就无法“一键回复”。 之前试过“重置回帖数据”，之后操作也是可以一键回复，现在重新安装脚本，依然无效。 是不是网站后台识别我是刷评论，望作者大大更新脚本，谢谢
> > 
> > 
> > 新人报道专区，许多人的回复下自带超链接，比如“歡迎來到捷克論壇~~ 請多多指教~也可以加我好友互相解任務喔~ 另外~~~ 小弟在申請好市民徽章， 請大大給予愛心並關注， 小弟也會盡力回送愛心~ 請點下方的網址給予我愛心， 感謝您了~
> > [https://www.jkforum.net/thread-17296783-1-1.html”](https://www.jkforum.net/thread-17296783-1-1.html%E2%80%9D) 请问能否增加推广报道主页和个人空间主页的超链接功能，感谢。部分帖子需要100权限，努力刷到100
> 
> 输入框一直是支持富文本的。在论坛编辑器的高级模式里编辑好，可以去复制别人的，点右上角纯文本，复制到回复里就可以回复富文本了。

已添加超链接，谢谢。发现我的道具积累很多，从未使用过。使用需要单个点击，太麻烦，可否设置自动使用。
发表日志可增加名声，可否设置自动发表3篇日志。
升到100权限，还需2年多，名声太难获取。依然谢谢您了
