### ISSUE TITLE
请问能否限制图片的展示张数

### ISSUE THREAD

**Issue by lyjhyjyes** [Eished/jkforum_helper#2]
https://www.jkforum.net/forum.php?mod=viewthread&tid=13820229&extra=page%3D1%26filter%3Dtypeid%26typeid%3D521%26typeid%3D521
因为国内用代理上，网络不稳定，打开多图片的容易卡死，特别是200P/300P，没必要看完全部。请问能不能指定看第50-80张这样子

**Comment by Eished** [comment]
网站本身有控制同时加载数量为10张，加载完上一张才会加载下一张，不会出现卡死的情况。

**Comment by Eished** [comment]
> https://www.jkforum.net/forum.php?mod=viewthread&tid=13820229&extra=page%3D1%26filter%3Dtypeid%26typeid%3D521%26typeid%3D521
> 因为国内用代理上，网络不稳定，打开多图片的容易卡死，特别是200P/300P，没必要看完全部。请问能不能指定看第50-80张这样子

新版增加了屏蔽图片功能，可以解决这个问题
