### ISSUE TITLE
0.57版本不能自动阅读全文 加载全图

### ISSUE THREAD

**Issue by henry16851** [Eished/jkforum_helper#3]
昨天更新0.57版本发现这个问题, 之前0.56版本打开帖子自动会点击全文和加载全图

![image](https://user-images.githubusercontent.com/33363247/126418558-bbd85cd3-fd0f-4325-8d0d-9ac74ac14f28.png)

**Comment by Eished** [comment]
> 昨天更新0.57版本发现这个问题, 之前0.56版本打开帖子自动会点击全文和加载全图
> 
> ![image](https://user-images.githubusercontent.com/33363247/126418558-bbd85cd3-fd0f-4325-8d0d-9ac74ac14f28.png)

我测试功能都正常的，检查是否开启了自动感谢，F12看控制台有无报错，没报错的话发帖子链接，我试下。

**Comment by henry16851** [comment]
> > 昨天更新0.57版本发现这个问题, 之前0.56版本打开帖子自动会点击全文和加载全图
> > ![image](https://user-images.githubusercontent.com/33363247/126418558-bbd85cd3-fd0f-4325-8d0d-9ac74ac14f28.png)
> 
> 我测试功能都正常的，检查是否开启了自动感谢，F12看控制台有无报错，没报错的话发帖子链接，我试下。

我系统是big sur 11.2.3, Safari 14.0.3 油猴, 所有功能都开启了, 你试试这个链接

![image](https://user-images.githubusercontent.com/33363247/126582267-c7a71449-8d42-4ac4-bfdd-59a88acc4ae1.png)

https://www.jkforum.net/thread-13829659-1-1.html

**Comment by Eished** [comment]
> > > 昨天更新0.57版本发现这个问题, 之前0.56版本打开帖子自动会点击全文和加载全图
> > > ![image](https://user-images.githubusercontent.com/33363247/126418558-bbd85cd3-fd0f-4325-8d0d-9ac74ac14f28.png)
> > 
> > 
> > 我测试功能都正常的，检查是否开启了自动感谢，F12看控制台有无报错，没报错的话发帖子链接，我试下。
> 
> 我系统是big sur 11.2.3, Safari 14.0.3 油猴, 所有功能都开启了, 你试试这个链接
> 
> ![image](https://user-images.githubusercontent.com/33363247/126582267-c7a71449-8d42-4ac4-bfdd-59a88acc4ae1.png)
> 
> https://www.jkforum.net/thread-13829659-1-1.html

可能是浏览器或插件不兼容，目前只测试了 Win + Chrome ，没有测试 Safari 的环境。
0.5.5 到 0.5.7 没有改动自动感谢，如果以前可以用要退回到 0.5.4，但自动感谢改动部分不会影响兼容性。
