### ISSUE TITLE
网站强制绑定手机号，导致账户无法登录

### ISSUE THREAD

**Issue by lyjhyjyes** [Eished/jkforum_helper#8]
旧账户无法登录，无法绑定国内大陆的86手机号，请问有办法吗

**Comment by Eished** [comment]
Google Voice 之类的虚拟号码试试。

**Comment by lyjhyjyes** [comment]
> Google Voice 之类的虚拟号码试试。

请问非登录状态，是否原图显示图片

**Comment by Eished** [comment]
> 请问非登录状态，是否原图显示图片

非登录状态脚本不运行，所以不会显示原图

**Comment by Eished** [comment]
> 旧账户无法登录，无法绑定国内大陆的86手机号，请问有办法吗

我已经可以跳过手机号验证，等我有时间尝试用脚本跳过再更新。

**Comment by Eished** [comment]
@lyjhyjyes 跳过手机验证码功能已经发布了，欢迎测试 ━(*｀∀´*)ノ亻!

**Comment by lyjhyjyes** [comment]
> @lyjhyjyes 跳过手机验证码功能已经发布了，欢迎测试 ━(_｀∀´_)ノ亻!

感谢，节点到期，周一再试

**Comment by lyjhyjyes** [comment]
您好，请问可否删除本人在该脚本下的所有帖子，谢谢
